# Generated by Django 5.0.7 on 2024-07-13 15:45

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('type_food', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('both', 'For Both Veg and NonVeg')], max_length=7)),
                ('menu_catagory', models.CharField(choices=[('juice', 'Juice'), ('Starter', 'Veg Starter'), ('NStarter', 'Non-Veg Starter'), ('Vmain', 'Veg Main Course'), ('Nmain', 'Non-Veg Main Course'), ('BRD', 'Veg Bread,Rice,Noodles'), ('NBRD', 'Non-Veg Bread,Rice,Noodles'), ('dessert', 'Dessert')], max_length=50)),
                ('food_image', models.FileField(default=None, max_length=250, null=True, upload_to='food/')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='caterer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caterer_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='caterer/')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('deliverable_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_delivery_till_km', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_for_food', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_order_night', models.IntegerField(default=0)),
                ('max_order_day', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('both', 'Both')], max_length=7)),
                ('gstin_number', models.CharField(max_length=15)),
                ('advance_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatarerFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catrinmodel.food')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCatagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg_starters_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nonveg_starters_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg_main_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nonveg_main_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg_bread_rice_noodle_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nonveg_bread_rice_noodle_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dessert_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caterer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_time', models.CharField(max_length=100)),
                ('ordered_food_list', models.TextField()),
                ('order_day', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=7)),
                ('delivery_date', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('function_name', models.CharField(max_length=100)),
                ('food_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gstin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_member_veg', models.IntegerField()),
                ('total_member_nonveg', models.IntegerField()),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('caterer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_caterer', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('accountno', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('bank_type', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('paid_time', models.DateTimeField()),
                ('caterer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_caterer', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
