# Generated by Django 5.0.7 on 2024-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterer',
            name='isavailable',
            field=models.BooleanField(default=True),
        ),
    ]
