# Generated by Django 5.0.7 on 2024-07-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0002_caterer_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deliveried', 'Deliveried')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
