# Generated by Django 5.0.7 on 2024-11-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_food_list',
        ),
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catrinmodel.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='catrinmodel.order')),
            ],
        ),
    ]
