# Generated by Django 5.0.7 on 2024-12-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0007_bankdetails_cancelleditems_catererfood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='caterer_id',
        ),
        migrations.CreateModel(
            name='MenuCategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg_starters_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nonveg_starters_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg_main_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nonveg_main_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('veg_bread_rice_noodle_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nonveg_bread_rice_noodle_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dessert_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catrinmodel.cateringbranch')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
