# Generated by Django 5.0.7 on 2024-12-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0008_remove_order_caterer_id_menucategorydetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='caterer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caterer_orders', to='catrinmodel.cateringbranch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='caterer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caterer_bank_details', to='catrinmodel.cateringbranch'),
        ),
    ]
