# Generated by Django 5.0.7 on 2024-12-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0012_alter_order_note'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cateringbranch',
            name='unique_branch_name_per_catering_service',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='caterer',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='catererfood',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='catererfood',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='cateringpackage',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='caterer',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='caterer',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='phonecontact',
            old_name='caterer',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='caterer',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_branch',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_details', to='catrinmodel.cateringbranch'),
        ),
        migrations.AddConstraint(
            model_name='cateringbranch',
            constraint=models.UniqueConstraint(fields=('branch_id', 'branch_name'), name='unique_branch_name_per_catering_service'),
        ),
    ]
