# Generated by Django 5.0.7 on 2024-12-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0013_remove_cateringbranch_unique_branch_name_per_catering_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catererfood',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
