# Generated by Django 5.0.7 on 2024-12-21 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0015_alter_cateringpackage_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catererfood',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
