# Generated by Django 5.0.7 on 2024-12-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0016_alter_catererfood_extra_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_orders', to='catrinmodel.order')),
            ],
        ),
        migrations.DeleteModel(
            name='CancelledItems',
        ),
    ]
