# Generated by Django 5.0.7 on 2024-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0017_cancelledorder_delete_cancelleditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecontact',
            name='phone_type',
        ),
        migrations.AddField(
            model_name='phonecontact',
            name='contact_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
