# Generated by Django 5.0.7 on 2025-05-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0018_remove_phonecontact_phone_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='dessert_cost',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='juice',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='nonveg_bread_rice_noodle_cost',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='nonveg_main_cost',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='nonveg_starters_cost',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='veg_bread_rice_noodle_cost',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='veg_main_cost',
        ),
        migrations.RemoveField(
            model_name='menucategorydetails',
            name='veg_starters_cost',
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('juice', 'Juice'), ('veg_starters', 'Veg Starters'), ('nonveg_starters', 'Nonveg Starters'), ('veg_main', 'Veg Main Course'), ('nonveg_main', 'Nonveg Main Course'), ('veg_bread_rice_noodle', 'Veg Bread/Rice/Noodle'), ('nonveg_bread_rice_noodle', 'Nonveg Bread/Rice/Noodle'), ('dessert', 'Dessert')], max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catrinmodel.menucategorydetails')),
            ],
        ),
    ]
