# Generated by Django 5.0.7 on 2025-05-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0020_remove_food_menu_catagory_food_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='catrinmodel.menucategory'),
        ),
    ]
