# Generated by Django 5.0.7 on 2025-05-14 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0021_alter_food_menu_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='menu',
        ),
        migrations.AddField(
            model_name='menucategorydetails',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='menucategorydetails',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catrinmodel.menucategory'),
        ),
    ]
