# Generated by Django 5.0.7 on 2025-05-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0022_remove_menucategory_cost_remove_menucategory_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategorydetails',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catrinmodel.menucategory'),
        ),
    ]
