# Generated by Django 5.0.7 on 2025-05-15 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrinmodel', '0023_alter_menucategorydetails_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='name',
            field=models.CharField(choices=[('juice', 'Juice'), ('veg_starters', 'Veg Starters'), ('nonveg_starters', 'Nonveg Starters'), ('veg_main', 'Veg Main Course'), ('nonveg_main', 'Nonveg Main Course'), ('veg_bread_rice_noodle', 'Veg Bread/Rice/Noodle'), ('nonveg_bread_rice_noodle', 'Nonveg Bread/Rice/Noodle'), ('dessert', 'Dessert')], max_length=50, unique=True),
        ),
    ]
